"""Personality integration for Spark Intelligence Builder.

Loads personality chip profiles, manages per-user trait preferences
via runtime_state, provides personality context for the advisory pipeline,
and self-evolves based on observed user interactions.
"""

from spark_intelligence.personality.loader import (
    AgentOnboardingTurnResult,
    AgentPersonaMutationResult,
    LegacyPersonalityMigrationResult,
    PersonalityImportResult,
    PersonalityQueryResult,
    apply_telegram_surface_persona,
    build_telegram_surface_identity_preamble,
    build_personality_import_payload,
    build_personality_context,
    build_preference_acknowledgment,
    create_agent_persona_savepoint,
    detect_and_persist_agent_persona_preferences,
    detect_and_persist_nl_preferences,
    detect_personality_query,
    list_agent_persona_savepoints,
    load_agent_persona_profile,
    load_personality_profile,
    maybe_handle_agent_persona_onboarding_turn,
    migrate_legacy_human_personality_to_agent_persona,
    maybe_evolve_traits,
    normalize_personality_import,
    pop_agent_persona_undo_snapshot,
    push_agent_persona_undo_snapshot,
    record_observation,
    restore_agent_persona_savepoint,
    resolve_builder_persona_agent_id,
    resolve_personality_evolver_state_path,
    save_agent_persona_profile,
    write_personality_evolver_state,
)

__all__ = [
    "AgentOnboardingTurnResult",
    "AgentPersonaMutationResult",
    "LegacyPersonalityMigrationResult",
    "PersonalityImportResult",
    "PersonalityQueryResult",
    "apply_telegram_surface_persona",
    "build_telegram_surface_identity_preamble",
    "build_personality_import_payload",
    "build_personality_context",
    "build_preference_acknowledgment",
    "create_agent_persona_savepoint",
    "detect_and_persist_agent_persona_preferences",
    "detect_and_persist_nl_preferences",
    "detect_personality_query",
    "list_agent_persona_savepoints",
    "load_agent_persona_profile",
    "load_personality_profile",
    "maybe_handle_agent_persona_onboarding_turn",
    "migrate_legacy_human_personality_to_agent_persona",
    "maybe_evolve_traits",
    "normalize_personality_import",
    "pop_agent_persona_undo_snapshot",
    "push_agent_persona_undo_snapshot",
    "record_observation",
    "restore_agent_persona_savepoint",
    "resolve_builder_persona_agent_id",
    "resolve_personality_evolver_state_path",
    "save_agent_persona_profile",
    "write_personality_evolver_state",
]
