"""Generate a human-readable MD report of the NL intent matrix.

Runs the same matrix as `tests/test_nl_intent_matrix.py` but writes the
per-phrase results to `docs/NL_TEST_RESULTS.md`. Intended to be
regenerated after any NL change so you can see the full behavior table
without reading raw pytest output.

Usage:
    python -m tests.generate_nl_test_report
"""
from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path

# Make src importable when run as a script from the repo root
REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))
sys.path.insert(0, str(REPO / "tests"))

from test_nl_intent_matrix import (  # noqa: E402
    FIXTURE_BY_INTENT,
    INTENT_DETECTORS,
    INTENT_PRIORITY,
    PLAIN_CHAT_PHRASES,
    STATEFUL_DETECTORS,
)


def _resolve(phrase: str) -> tuple[str | None, list[str]]:
    hits = [
        name
        for name, det in INTENT_DETECTORS.items()
        if name not in STATEFUL_DETECTORS and det(phrase)
    ]
    if not hits:
        return None, []
    winner = min(
        hits,
        key=lambda n: INTENT_PRIORITY.index(n) if n in INTENT_PRIORITY else 999,
    )
    return winner, hits


def main() -> int:
    out_path = REPO / "docs" / "NL_TEST_RESULTS.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    total_positive = sum(len(v) for v in FIXTURE_BY_INTENT.values())
    total_anti = len(PLAIN_CHAT_PHRASES)

    lines: list[str] = []
    lines.append("# Spark NL Intent Matrix - Test Results")
    lines.append("")
    lines.append(f"**Generated:** {generated_at}")
    lines.append(f"**Intents tracked:** {len(FIXTURE_BY_INTENT)}")
    lines.append(f"**Positive fixtures:** {total_positive}")
    lines.append(f"**Plain-chat anti-fixtures:** {total_anti}")
    lines.append("")
    lines.append(
        "This file is auto-generated by "
        "`tests/generate_nl_test_report.py`. Regenerate after any NL change."
    )
    lines.append("")
    lines.append("## Priority order (collision resolution)")
    lines.append("")
    lines.append(
        "When a phrase matches multiple detectors, the one earlier in this "
        "list wins. Mirrors the telegram adapter's short-circuit sequence "
        "per the `conversational-intent-design` H70-C+ skill."
    )
    lines.append("")
    for i, intent in enumerate(INTENT_PRIORITY, 1):
        lines.append(f"{i}. `{intent}`")
    lines.append("")
    lines.append(
        "Stateful detectors (only meaningful when pending state exists) "
        f"are exempt from the priority audit: {sorted(STATEFUL_DETECTORS)}"
    )
    lines.append("")

    # --- Per-intent positive fixture section ---
    lines.append("## Positive fixtures (must match their declared intent)")
    lines.append("")
    grand_pass = 0
    grand_fail: list[str] = []
    for intent, phrases in FIXTURE_BY_INTENT.items():
        lines.append(f"### `{intent}` ({len(phrases)} fixtures)")
        lines.append("")
        lines.append("| Phrase | Expected | Resolved to | Other hits | Status |")
        lines.append("|---|---|---|---|---|")
        for phrase in phrases:
            if intent in STATEFUL_DETECTORS:
                fires = INTENT_DETECTORS[intent](phrase)
                status = "PASS" if fires else "FAIL"
                resolved = intent if fires else "-"
                other = "-"
            else:
                winner, hits = _resolve(phrase)
                resolved = winner or "-"
                other_hits = [h for h in hits if h != winner]
                other = ", ".join(f"`{h}`" for h in other_hits) if other_hits else "-"
                status = "PASS" if winner == intent else "FAIL"
            if status == "PASS":
                grand_pass += 1
            else:
                grand_fail.append(f"{intent}: {phrase!r} -> {resolved}")
            phrase_cell = f"`{phrase}`".replace("|", "\\|")
            lines.append(f"| {phrase_cell} | `{intent}` | `{resolved}` | {other} | {status} |")
        lines.append("")

    # --- Anti-fixtures section ---
    lines.append("## Plain-chat anti-fixtures (must match nothing)")
    lines.append("")
    lines.append("| Phrase | Matched | Status |")
    lines.append("|---|---|---|")
    for phrase in PLAIN_CHAT_PHRASES:
        hits = [
            name
            for name, det in INTENT_DETECTORS.items()
            if det(phrase)
        ]
        status = "PASS" if not hits else "FAIL"
        if status == "PASS":
            grand_pass += 1
        else:
            grand_fail.append(f"anti-fixture: {phrase!r} -> {hits}")
        matched = ", ".join(f"`{h}`" for h in hits) if hits else "-"
        phrase_cell = f"`{phrase}`".replace("|", "\\|")
        lines.append(f"| {phrase_cell} | {matched} | {status} |")
    lines.append("")

    # --- Summary ---
    total_tests = grand_pass + len(grand_fail)
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Total checks:** {total_tests}")
    lines.append(f"- **Passed:** {grand_pass}")
    lines.append(f"- **Failed:** {len(grand_fail)}")
    if grand_fail:
        lines.append("")
        lines.append("### Failures")
        lines.append("")
        for f in grand_fail:
            lines.append(f"- {f}")
    lines.append("")

    # --- How to use ---
    lines.append("## Adding a new intent")
    lines.append("")
    lines.append("1. Implement the detector in its bridge module.")
    lines.append("2. Add positive fixtures to `FIXTURE_BY_INTENT` in")
    lines.append("   `tests/test_nl_intent_matrix.py`.")
    lines.append("3. Register the detector in `INTENT_DETECTORS`.")
    lines.append("4. Add the intent to `INTENT_PRIORITY` in the right position.")
    lines.append("5. Run: `python -m pytest tests/test_nl_intent_matrix.py`")
    lines.append("6. Regenerate this file: `python -m tests.generate_nl_test_report`")
    lines.append("")
    lines.append("Per the H70-C+ `conversational-intent-design` skill:")
    lines.append("- Rules (tier 1) for the hot path; LLM (tier 2) only for long tail.")
    lines.append("- Intents must be disjoint (or priority must be declared).")
    lines.append("- Destructive intents require a confirmation gate.")
    lines.append("- Outputs must be conversational, not field dumps.")
    lines.append("- Register / tone matching where possible.")
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out_path}")
    print(f"  checks: {total_tests}")
    print(f"  passed: {grand_pass}")
    print(f"  failed: {len(grand_fail)}")
    return 0 if not grand_fail else 1


if __name__ == "__main__":
    raise SystemExit(main())
